language: cpp
os: linux
dist: focal
compiler: gcc

script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DDCONV_ENABLE_TESTS=ON ..
  - cmake --build . -j $(nproc)
  - ctest -vv
