name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: joinframework/join-ci:latest

    steps:
    - name: Fetch
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -G "Unix Makefiles" -B /__w/dconv/dconv/build -DCMAKE_BUILD_TYPE=Debug -DDCONV_ENABLE_TESTS=ON -DDCONV_ENABLE_COVERAGE=ON

    - name: Build
      run: cmake --build /__w/dconv/dconv/build --config Debug

    - name: Test
      run: ctest --test-dir /__w/dconv/dconv/build --output-on-failure -C Debug

    - name: Generate coverage report
      run: lcov --directory . --capture --output-file lcov.info

    - name: Cleanup coverage report
      run: lcov --remove lcov.info '/__w/dconv/dconv/build/*' '/__w/dconv/dconv/dconv/tests/*' '/usr/include/*' --output-file lcov.info

    - name: Deploy coverage report to coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{secrets.github_token}}
        path-to-lcov: /__w/dconv/dconv/lcov.info

    - name: Deploy coverage report to codecove
      uses: codecov/codecov-action@v2
      with:
        file: /__w/dconv/dconv/lcov.info
