name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: joinframework/join-ci:latest
      options: --privileged

    steps:
    - name: Fetch
      uses: actions/checkout@v3.0.2

    - name: Configure CMake
      run: cmake -G "Unix Makefiles" -B /__w/dconv/dconv/build -DCMAKE_BUILD_TYPE=Debug -DDCONV_ENABLE_TESTS=ON -DDCONV_ENABLE_COVERAGE=ON

    - name: Build
      run: cmake --build /__w/dconv/dconv/build --config Debug

    - name: Test
      run: ctest --test-dir /__w/dconv/dconv/build --output-on-failure -C Debug

    - name: Generate coverage report
      run: lcov --directory . --capture --output-file lcov.info

    - name: Cleanup coverage report
      run: lcov --remove lcov.info '/__w/dconv/dconv/build/*' '/__w/dconv/dconv/dconv/tests/*' '/usr/include/*' --output-file lcov.info

    - name: Deploy coverage report to coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: /__w/dconv/dconv/lcov.info

    - name: Deploy coverage report to codecove
      uses: codecov/codecov-action@v3.1.0
      with:
        fail_ci_if_error: true
        token: ${{secrets.CODECOV_TOKEN}}
        file: /__w/dconv/dconv/lcov.info
        flags: unittests

    - name: Deploy coverage report to codacy
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
        coverage-reports: /__w/dconv/dconv/lcov.info
